sudo: required

services:
  - docker

env:
  global:
    - VERSION=0.10.4
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=fail2ban
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=fail2ban
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/fail2ban/2vi2BNDE1QSKs_ZUGC4tfBy23X0=
    - secure: UDRJ6IAOOPj8zOjZw3HnJCpx3JKyMvG5mTAQYHXrPfUICbLUUPLqVxzIqRuVG/3/c1YqIwrvf/MnLZzNi7JpVjsjXrKWpbG9jJYX+iAiJUE3DJS7R8w6LLL62u0L6rULUmB4sK6rCKrs1gm5ijEBl4ATqIGL9jKHWD7dxw3KcL/Ds0xc6WaUKLeRPYMs6Dqsh40tbv2Pro7AzBeY/sOUMNf6bSjrAgV8C2rkj50fw3QidTTkqhaUoPT6JpRrZRAwu2thQ5Lb6+Jv2R8iLSGXeogf6yMAvWPwfZk6UryH7NjrGEhlvua6IRRkUNW8BLuoL7ZDCiumOlCrfHyjqgox0yRSnhThqUmRfLsZEFKpoXUUN7gRGQXqP828MqnX9Y5Rg1sAW5trWARYw7PBZOvqLCWRR8XYK0g5Ynq+eK3fBAmMtkbZToaH/VNvvPh3g/Yi+4n9kLJqdfAOYqnArI2ONF5ibsIN2v3ldfhWgHkC7jI8wL4R8ZTgcyUXKHXSCCmKE5KJSz/o1vLwkDrJmxCPmNSgaGs+rG9Qh5wYQBdm7GFd4fvAbaxKAjQonpU4dqmg+cnqBqBG5Knw8KgbJ/Fiq+acRA9UaCDElGmRyVUNV2UrwOd1JKjse/oV7OSr1auYLK/Uem/NPzGLAlhVb28wOuiHYI8UilPgz80veyqXMwA= # DOCKER_PASSWORD
    - secure: THe54Rp3WZ8WjJx3jvIfg+eKh5u1XGlb23BZNLVFaM51+Ijk5Ci9ETJnldtrPPK0Zvjl6opgyL/0u4xj0peY68/lP49wFWlRzW0HZWWag0Q8Z0hXt5Ho9QcvZzLcgqyv3rk5sacv+mc+g14Wke5OCM1i8y7V8+KjiBAqZ6ScEb791gVXutI30mQybnE59dEboLzigqahZQ3mVFOk1G3kvqfHjNyVudRNQ0Hi9Qjh2ey7AYbgDW6uCf1lT2o2eAt90KY1yF7bgdJ1uzng6Z+yArNDbnfi0hK+lDtyIZpgPKJ0GiV/Z+brV+XhmL3lC0+8Ak3VmvC5sSEVBLycfp56eu9riKcxF6P7DAzJVUPFkcwO+Kp6tGGX+gpw2tBJzuze7nUGiPKDYOGbIjQI8I8xMIlizysS4UaFU8muJeh8lSpCQq1A2uznMSxVxmmlN1uJskiCle5zgFGuCzrz2we24sgjy2FGq45nBg4fby8ocNf42+lcK+NnO6+dPw0TnJR7Uxs21RkPxCtoIsTZBlOOWwBy2uagm7qzLeUwEe7asZzQ8u1V27sSKYqOj8pOLLF+eH0GE7dr0/3p//FqbQvw0v0Mf2R+Zx3cSq2PH9JLrWMOZLuKSrgJK+M5NO1JXfVH0g/UppQDe1SZl99RL9aXvqsjt7kHKoERSEInnNWVckg= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  webhooks:
    secure: aJJpja0WapGFAshedDpDSxAP/+C1R4YNooXGRATVd+Na0lMmrSEGr+l52ougIAgZMoIdS0wOExK7bEGncc5BDIG4PSSOgaG3oKkGIc3TgKnLkMvygmYN+3pUUzhMeajQGT2LhkAzHb4fb/3z9U4caufFpzBs+RVI31rVP83Mrk1NuoIUg0fyivIebyddgOdHmDCGCnp7aW/pLtrnMeKDsFICvXeBE7cr9CWEnt2MZxNeVmCQ9fKrcEbDENRwZGD41+E8d8aGPxB6UYKdZMmitsgQH1kXE72Q54T/GZTtrGmV7zpijtKMxD48caNMdqLUCi+GxYF49RDDRNGkoZ9cy4EvmiOrpL1UUCCXFIkMcatuxlJ5VmT+uoIU+uue923nZTHCf5LC64WM4jkd/NxoZ6liG5cI2Hcxgvr65dhcHKJ0hibUkP6FBp/u2BzyAv40RxY+WG3DInmVcmtgcnzBCC0twa6Nodg1rTxaIedf+zd63bM3a/1UVWBnTbFv6iJOJTu6IRpRZz8YNucDGZUcmQ09aLnAATFiEXRkvA8ONoMcl3UlhDTzP4YNYOjwlKGxT1g05NJRqjAH+utzcffCJ2k7r5SoojjMq6SnhQFHNTzLMNXRBBBnju6bXa0jNum12nFphJHzXMUSw+PHIhffqrL4p5vJ6GU77doPxRPVM/U=
