version: "3.2"

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./db:/var/lib/fail2ban"
      - "./jail.d:/etc/fail2ban/jail.d:ro"
      - "/var/log:/var/log:ro"
    env_file:
      - "./fail2ban.env"
    restart: always
